apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-oci
  namespace: podinfo
spec:
  interval: 10m
  sourceRef:
    kind: OCIRepository
    name: podinfo
  path: ./deploy/production
  wait: true
  prune: true
