---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo
  namespace: podinfo
spec:
  git:
    checkout:
      ref:
        branch: dev
    commit:
      author:
        email: yebyen+fluxcd@gmail.com
        name: fluxcdbot
      messageTemplate: '[ci skip] {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: dev
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: podinfo-rw
  update:
    path: ./kustomize
    strategy: Setters
