apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  rules:
  - host: podinfo.demos.hephy.pro
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - podinfo.demos.hephy.pro
    secretName: podinfo-stg-tls
